DROP TABLE BOARD_TB;

CREATE TABLE BOARD_TB(
    BNO NUMBER(10) PRIMARY KEY,
    TITLE VARCHAR2(500) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    WRITER VARCHAR2(100) NOT NULL,
    IMAGEfILENAME VARCHAR2(100),
    WRITEDATE DATE DEFAULT SYSDATE
);

DROP SEQUENCE BNO_SEQ;
CREATE SEQUENCE BNO_SEQ;

INSERT INTO board_tb(bno,title,content,writer)
VALUES (bNO_SEQ.NEXTVAL,'제목1','내용1','관리자');
INSERT INTO board_tb(bno,title,content,writer)
VALUES (bNO_SEQ.NEXTVAL,'제목2','내용2','관리자');

SELECT * FROM BOARD_TB;

COMMIT;

--테이블 컬럼추가
ALTER TABLE BOARD_TB ADD REPLYCOUNT INT;
