DROP TABLE MEMBER_TB;

CREATE TABLE MEMBER_TB(
    MNO INT PRIMARY KEY,
    ID VARCHAR2(60) NOT NULL UNIQUE,
    PWD VARCHAR2(100),
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(2000),
    PHONE VARCHAR2(50),
    JOINDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE MNO_SEQ;
DROP SEQUENCE MNO_SEQ;

INSERT INTO MEMBER_TB(MNO,ID,PWD, NAME, EMAIL, PHONE)
VALUES(MNO_SEQ.NEXTVAL,'lee','1234','이창우','lee@example.com','010-1111-1111');
INSERT INTO MEMBER_TB(MNO,ID, PWD, NAME, EMAIL, PHONE)
VALUES(MNO_SEQ.NEXTVAL,'kim','1234','김창우','kim@example.com','010-2222-2222');

alter table MEMBER_TB add GRADE VARCHAR2(30) DEFAULT 'ROLE_MEMBER';

--update MEMBER_TB set grade='ROLE_ADMIN' where id='admin';

select * from MEMBER_TB;

COMMIT;